### ISSUE TITLE
Check Box

### ISSUE THREAD

**Issue by x-dean** [BaldissaraMatheus/Tasks.md#133]
Greetings,

Thanks for this good work!

I am not sure if it can be done right now (from what I tested I failed to do it), but some check boxes would be very good to be available.

Checkboxes are supported in md => [Link](https://www.markdownguide.org/extended-syntax/#task-lists)

Thank you

**Comment by BaldissaraMatheus** [comment]
Yeah, it's actually the most requested feature, and it's lacking because of the editor the app uses doesn't support it. It requires a big change and may take some time, but It's going to be the next thing I'll work on.

I'll close this issue because it's already being tracked on #76, please follow that one and feel free to participate in the discussion there
