### ISSUE TITLE
Delete confirmation prompt

### ISSUE THREAD

**Issue by kernelkaribou** [BaldissaraMatheus/Tasks.md#24]
### Feature Request

It would be nice to have some kind of confirmation for deleting a task or lane. Currently a misclick could wipe out any number of tasks if a lane is deleted or a task itself.

Another idea could be some kind of trash can, maybe the flat file gets renamed so its parsed as deleted. Either push it to the bottom of the lane so its always active tasks and then deleted ones or something like that. If not just making sure a delete isn't so easily destructive.  

Having some kind of status parsing design could be nice if there was ever a desire to mark a task complete rather than moving it to a lane, like a more traditional Todo, task app. Just a thought.

Appreciate the project and as soon as I saw it shared on /r/selfhosted I thought this was the simple project I was waiting for, just a couple quality of life improvements I could see which would make it perfect, for me of course :)

Thanks for this.

**Comment by BaldissaraMatheus** [comment]
About the confirmation prompt, do you think it should be a full screen alert message or a less intrusive dialog option?
![image](https://user-images.githubusercontent.com/19363147/225697185-af7bf274-a769-4818-a19a-437b4fd09d8a.png)
![image](https://user-images.githubusercontent.com/19363147/225697098-890c2702-d0bf-4f81-9306-e8a9c3a1ba85.png)

I think I like the second option more, but I'm still not convinced

**Comment by BaldissaraMatheus** [comment]
About marking the task as completed, I did some research to see how different applications handle this, and it seems that some them have a checkbox to set as complete, some have a "completed" lane and some have neither (for example Nextcloud Deck).

I think if we included a "completed" checkbox, it should be linked to a lane that contains all the completed cards, because I think most people would like to have a lane for completed tasks (but I could be wrong here, idk) and it would be confusing if this lane was disconnected from the checkbox. But to acomplish this it would need to have completed lane as required in the first place, adding complexity to the app and losing a little of its flexibility.

But I think board based applications are more useful when you want to have mutliple steps or stages for the tasks, so the natural flow would be moving a card from one stage to another, instead of a todo/done toggle. So for this purpose I think the application works just fine.

I was also thinking in adding a "delete all cards" option for the lane options to make it easier cleaning up done tasks when it's no longer useful keeping them. I'll focus on the delete confirmation prompt first though.

**Comment by kernelkaribou** [comment]
> About the confirmation prompt, do you think it should be a full screen alert message or a less intrusive dialog option? ![image](https://user-images.githubusercontent.com/19363147/225697185-af7bf274-a769-4818-a19a-437b4fd09d8a.png) ![image](https://user-images.githubusercontent.com/19363147/225697098-890c2702-d0bf-4f81-9306-e8a9c3a1ba85.png)
> 
> I think I like the second option more, but I'm still not convinced

I think the second one is good too.

**Comment by kernelkaribou** [comment]
> About marking the task as completed, I did some research to see how different applications handle this, and it seems that some them have a checkbox to set as complete, some have a "completed" lane and some have neither (for example Nextcloud Deck).
> 
> I think if we included a "completed" checkbox, it should be linked to a lane that contains all the completed cards, because I think most people would like to have a lane for completed tasks (but I could be wrong here, idk) and it would be confusing if this lane was disconnected from the checkbox. But to acomplish this it would need to have completed lane as required in the first place, adding complexity to the app and losing a little of its flexibility.
> 
> But I think board based applications are more useful when you want to have mutliple steps or stages for the tasks, so the natural flow would be moving a card from one stage to another, instead of a todo/done toggle. So for this purpose I think the application works just fine.
> 
> I was also thinking in adding a "delete all cards" option for the lane options to make it easier cleaning up done tasks when it's no longer useful keeping them. I'll focus on the delete confirmation prompt first though.

Makes total sense. I think if anything else, if there was a completed tasks method, putting in a completed lane would be nice. To your point most boards have that discipline of some kind of completed lane. Unless you were using a single lane, I would expect someone to create lane for holding completed/abandoned/archived cards. So that makes sense. 

In addition if you were prompted to confirm deleting then having some form of "trash" may not be necessary since you were asked twice, mistakes at that point is on the user.

**Comment by BaldissaraMatheus** [comment]
Just merged the prompt into the main branch
